# File: analysis_options.yaml
# File Version: 1.0.0
# Copyright (c) 2026 The Khatu Family Trust

include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
